export class Articlelist {
    societe = ""
    
    search = {
      reference: "",
      codeBarre: "",
      designation: "",
      typeArticle: "",
      categorie: "",
      famille: "",
      sousFamille: "",
      marque: "",
      modele: "",
      prixFourn: "",
      remiseF: "",
      marge: "",
      prixVenteHT: "",
      tauxTVA: "",
      montantTVA: "",
      prixAchat: "",
      prixAchatTTC: "",
      valeurStock: "",
      qteEnStock: "",
      prixTTC: "",
      plafondRemise: "",
      pVenteConseille: "",
      enVente: "",
      enAchat: "",
      refFournisseur: "",
      redevance: "",
      enBalance: "",
      enPromotion: "",
      enNouveau: "",
      longueur: "",
      largeur: "",
      hauteur: "",
      surface: "",
      volume: "",
      enDisponible: "",
      enArchive: "",
      enVedette: "",
      enLiquidation: "",
      description: "",
      observations: "",
      poids: "",
      couleur: "",
      unite1: "",
      unite2: "",
      coefficient: "",
      emplacement: "",
      raccourciPLU: "",
      prixVenteHT2: "",
      prixVenteHT3: "",
      seuilAlerteQTS: "",
      seuilRearpQTS: "",
      qteTheorique: ""
    }

    orderBy = {
      reference: 0,
      codeBarre: 0,
      designation: 0,
      typeArticle: 0,
      categorie: 0,
      famille: 0,
      sousFamille: 0,
      marque: 0,
      modele: 0,
      prixFourn: 0,
      remiseF: 0,
      marge: 0,
      prixVenteHT: 0,
      tauxTVA: 0,
      montantTVA: 0,
      prixAchat: 0,
      valeurStock: 0,
      QteEnStock: 0,
      prixTTC: 0,
      plafondRemise: 0,
      pVenteConseille: 0,
      enVente: 0,
      enAchat: 0,
      refFournisseur: 0,
      redevance: 0,
      enBalance: 0,
      enPromotion: 0,
      enNouveau: 0,
      longueur: 0,
      largeur: 0,
      hauteur: 0,
      surface: 0,
      volume: 0,
      enDisponible: 0,
      enArchive: 0,
      enVedette: 0,
      enLiquidation: 0,
      description: 0,
      observations: 0,
      poids: 0,
      couleur: 0,
      unite1: 0,
      unite2: 0,
      coefficient: 0,
      emplacement: 0,
      raccourciPLU: 0,
      prixVenteHT2: 0,
      prixVenteHT3: 0,
      seuilAlerteQTS: 0,
      seuilRearpQTS: 0,
      qteTheorique: 0
    }
    
    limit = 10
    page= 1
  
}
